# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"      # Tipo de dependencias
    directory: "/"                # Ruta donde está tu requirements.txt
    schedule:
      interval: "daily"           # Revisar actualizaciones diariamente
    open-pull-requests-limit: 5   # Máximo de PRs abiertos al mismo tiempo
    ignore:
      - dependency-name: "some-package-to-ignore"  # opcional
        versions:
          - ">=1.0.0"
